services:
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/:z # Add :z if using SELinux on Linux hosts.
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/
    depends_on:
      - db

  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public_html:/var/www/public_html:ro # Add :z if using SELinux on Linux hosts.
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

  composer:
    image: composer:latest
    container_name: composer_service
    volumes:
      - .:/app:z # Add :z if using SELinux on Linux hosts.
    working_dir: /app

  node:
    image: node:18-alpine
    container_name: node_service
    volumes:
      - .:/app:z # Add :z if using SELinux on Linux hosts.
    working_dir: /app

volumes:
  db_data:
